experiment_name: all_tricks

seed: 0
epochs: 30
batch_size: 128
learning_rate: 0.001
optimizer: Adam
loss: CrossEntropyLoss

use_augmentation: true
use_batchnorm: true
use_dropout: true
use_label_smoothing: true

dropout_p: 0.5
label_smoothing: 0.1

data_dir: data
results_file: results/metrics.csv
